// Datos de respaldo de especie para TaxonDetail.jsx cuando la API no trae
// taxonomía completa (mismo patrón que species/observationFallbackData.js,
// pero con forma distinta — se documentan por separado en vez de forzar
// una fusión de esquemas incompatibles en esta pasada).
export const SPECIES_FALLBACK = {
  'leucostethus fraterdanieli': {
    scientificName: 'Leucostethus fraterdanieli',
    author: 'Myers & Daly, 1976',
    commonName: 'Rana dardo de Daniel',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Dendrobatidae',
    genus: 'Leucostethus',
    speciesEpithet: 'fraterdanieli',
    iucn: 'EN',
    endemic: true,
    altitudeRange: { min: 400, max: 1100 },
    habitat: 'Bosque húmedo tropical, hojarasca',
    activity: 'Diurna',
    diet: 'Pequeños artrópodos (ácaros, colémbolos)',
    reproduction: 'Desarrollo directo — huevos terrestres, sin estadio larvario acuático',
    curiosity: 'Lleva el nombre del hermano de un científico colombiano. Cada registro es de alto valor para la ciencia.',
    threats: ['Deforestación', 'Pérdida de hábitat', 'Quitridiomicosis'],
    distribution: 'Endémica de Antioquia, Colombia — distribución muy restringida',
    whatIs: 'Leucostethus fraterdanieli es una rana pequeña de la familia Dendrobatidae, caracterizada por su coloración discreta en tonos marrones y líneas claras a lo largo del cuerpo. Habita bosques húmedos tropicales de Colombia, generalmente cerca de quebradas y zonas con abundante hojarasca. Es una especie diurna que se alimenta de pequeños invertebrados y cumple un papel importante en el equilibrio ecológico de los ecosistemas donde vive.',
    synonyms: [],
    morphology: {
      dorsal: 'Fondo oscuro con manchas azuladas o verdosas en dorso y flancos',
      ventral: 'Vientre oscuro con leve iridiscencia',
      size: 'LHC: ♂ 16–19 mm · ♀ 18–22 mm',
      diagnostics: ['Patrón de manchas azuladas / verdosas', 'Glándulas femorales presentes', 'Tamaño pequeño'],
    },
  },
  'rhinella horribilis': {
    scientificName: 'Rhinella horribilis',
    author: 'Cope, 1862',
    commonName: 'Sapo gigante',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Bufonidae',
    genus: 'Rhinella',
    speciesEpithet: 'horribilis',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 0, max: 1500 },
    habitat: 'Áreas abiertas, jardines, bordes de bosque',
    activity: 'Nocturna',
    diet: 'Insectos, invertebrados',
    reproduction: 'Reproducción acuática — desove en cadenas en cuerpos de agua',
    curiosity: 'Sus glándulas parotoides producen veneno que puede dañar mascotas. Es el anfibio más grande de Colombia.',
    threats: ['Tráfico de mascotas', 'Atropellamiento vial'],
    distribution: 'Amplia: tierras bajas tropicales de América',
    whatIs: 'El sapo de caña mesoamericano (Rhinella horribilis) es una de las especies de anfibios que componen el género Rhinella, que se incluye en la familia de los bufónidos. Este anuro es de tamaño grande y de hábitos terrestres. Se distribuye de manera nativa desde el extremo sur de Estados Unidos por el norte, hasta el extremo norte del Perú por el sur. Durante décadas fue considerado un sinónimo más moderno del sapo de caña amazónico (R. marina), hasta que en 2016 se lo rehabilitó como especie plena.',
    synonyms: ['Bufo marinus', 'Bufo horribilis'],
    morphology: {
      dorsal: 'Piel rugosa parda a grisácea',
      ventral: 'Vientre claro con manchas oscuras',
      size: 'LHC: ♂ hasta 17 cm · ♀ hasta 24 cm',
      diagnostics: ['Parotoides muy prominentes', 'Tamaño grande', 'Piel rugosa parda'],
    },
  },
  'dendrobates truncatus': {
    scientificName: 'Dendrobates truncatus',
    author: 'Cope, 1861',
    commonName: 'Rana dardo amarilla',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Dendrobatidae',
    genus: 'Dendrobates',
    speciesEpithet: 'truncatus',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 0, max: 1200 },
    habitat: 'Bosque húmedo, hojarasca',
    activity: 'Diurna',
    diet: 'Ácaros, colémbolos',
    reproduction: 'Desarrollo directo — huevos terrestres',
    curiosity: 'El color brillante funciona como señal de advertencia (aposematismo) para los depredadores.',
    threats: ['Pérdida de hábitat', 'Comercio ilegal'],
    distribution: 'Colombia: región Caribe y valles interandinos',
    whatIs: 'Dendrobates truncatus es una rana pequeña de colores llamativos perteneciente a la familia Dendrobatidae. Presenta tonalidades negras con líneas o manchas amarillas, verdes o azuladas que advierten sobre su toxicidad. Habita bosques húmedos tropicales, especialmente en Colombia, donde vive cerca del suelo entre la hojarasca y zonas húmedas. Se alimenta principalmente de pequeños insectos y otros artrópodos.',
    synonyms: [],
    morphology: {
      dorsal: 'Amarillo o naranja brillante con manchas negras',
      ventral: 'Amarillo pálido con manchas negras',
      size: 'LHC: 2.5–3.5 cm',
      diagnostics: ['Coloración aposemática amarillo-negro', 'Tamaño pequeño', 'Discos adhesivos'],
    },
  },
  'rhinella alata': {
    scientificName: 'Rhinella alata',
    author: 'Cope, 1868',
    commonName: 'Rhinella alata',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Bufonidae',
    genus: 'Rhinella',
    speciesEpithet: 'alata',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 0, max: 900 },
    habitat: 'Bosques húmedos tropicales, hojarasca',
    activity: 'Terrestre',
    diet: 'Pequeños invertebrados',
    reproduction: 'Desove en cuerpos de agua',
    curiosity: 'Se caracteriza por su cuerpo robusto y una distintiva cresta o “ala” sobre la cabeza.',
    threats: ['Destrucción de hábitat'],
    distribution: 'Tierras bajas del Pacífico y región Caribe de Colombia y Centroamérica',
    whatIs: 'Rhinella alata es un sapo pequeño de hábitos terrestres perteneciente a la familia Bufonidae. Se caracteriza por su cuerpo robusto, coloración café o marrón con patrones oscuros y una distintiva cresta o “ala” sobre la cabeza. Habita bosques húmedos tropicales de Centroamérica y parte del norte de Sudamérica, donde suele encontrarse entre la hojarasca alimentándose de pequeños invertebrados.',
    synonyms: [],
    morphology: {
      dorsal: 'Café o marrón con patrones oscuros',
      ventral: 'Vientre claro',
      size: 'Pequeño',
      diagnostics: ['Cresta cefálica o "ala" sobre la cabeza'],
    },
  },
  'pristimantis achatinus': {
    scientificName: 'Pristimantis achatinus',
    author: 'Cope, 1868',
    commonName: 'Cutín Común de Occidente',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Craugastoridae',
    genus: 'Pristimantis',
    speciesEpithet: 'achatinus',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 10, max: 1900 },
    habitat: 'Bosques húmedos, plantaciones, jardines',
    activity: 'Nocturna',
    diet: 'Insectos',
    reproduction: 'Desarrollo directo',
    curiosity: 'A diferencia de otras ranas, no pasa por la etapa de renacuajo en el agua; sus huevos tienen desarrollo directo.',
    threats: ['Degradación de hábitat'],
    distribution: 'Colombia, Ecuador y Panamá',
    whatIs: 'Pristimantis achatinus es una especie de anfibio anuro de la familia Craugastoridae. Se encuentra en Colombia, Ecuador y Panamá. Su hábitat natural son los bosques húmedos subtropicales o tropicales de tierras bajas, bosques húmedos de montañas tropicales o subtropicales, plantaciones, jardines rurales, áreas urbanas y zonas previamente boscosas ahora muy degradadas.',
    synonyms: [],
    morphology: {
      dorsal: 'Coloración variable de amarillo a café oscuro',
      ventral: 'Completamente liso',
      size: '♂ 30-40 mm · ♀ 48-64 mm',
      diagnostics: ['Vientre liso', 'Primer dedo de la mano más largo que el segundo'],
    },
  },
  'pristimantis acanthinus': {
    scientificName: 'Pristimantis achatinus',
    author: 'Cope, 1868',
    commonName: 'Cutín Común de Occidente',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Craugastoridae',
    genus: 'Pristimantis',
    speciesEpithet: 'achatinus',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 10, max: 1900 },
    habitat: 'Bosques húmedos, plantaciones, jardines',
    activity: 'Nocturna',
    diet: 'Insectos',
    reproduction: 'Desarrollo directo',
    curiosity: 'A diferencia de otras ranas, no pasa por la etapa de renacuajo en el agua; sus huevos tienen desarrollo directo.',
    threats: ['Degradación de hábitat'],
    distribution: 'Colombia, Ecuador y Panamá',
    whatIs: 'Pristimantis achatinus es una especie de anfibio anuro de la familia Craugastoridae. Se encuentra en Colombia, Ecuador y Panamá. Su hábitat natural son los bosques húmedos subtropicales o tropicales de tierras bajas, bosques húmedos de montañas tropicales o subtropicales, plantaciones, jardines rurales, áreas urbanas y zonas previamente boscosas ahora muy degradadas.',
    synonyms: [],
    morphology: {
      dorsal: 'Coloración variable de amarillo a café oscuro',
      ventral: 'Completamente liso',
      size: '♂ 30-40 mm · ♀ 48-64 mm',
      diagnostics: ['Vientre liso', 'Primer dedo de la mano más largo que el segundo'],
    },
  },
  'pristimantis paisa': {
    scientificName: 'Pristimantis paisa',
    author: 'Lynch & Duellman, 1997',
    commonName: 'Pristimantis paisa',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Craugastoridae',
    genus: 'Pristimantis',
    speciesEpithet: 'paisa',
    iucn: 'VU',
    endemic: true,
    altitudeRange: { min: 1800, max: 3100 },
    habitat: 'Bosques montanos húmedos',
    activity: 'Nocturna',
    diet: 'Pequeños insectos',
    reproduction: 'Desarrollo directo',
    curiosity: 'Es endémica de la cordillera Central de Antioquia.',
    threats: ['Pérdida y degradación de hábitat'],
    distribution: 'Antioquia, Colombia',
    whatIs: 'Pristimantis paisa es una especie de anfibio anuro endémica del departamento de Antioquia, Colombia, perteneciente a la familia Craugastoridae. Habita bosques montanos húmedos entre los 1800 y 3100 metros de altitud, donde presenta hábitos nocturnos. Esta rana cumple un papel importante en el equilibrio ecológico de los ecosistemas andinos, aunque actualmente enfrenta amenazas debido a la pérdida y degradación de su hábitat natural.',
    synonyms: [],
    morphology: {
      dorsal: 'Piel lisa o finamente granular',
      ventral: 'Grisáceo',
      size: 'Pequeño',
      diagnostics: ['Endémica de Antioquia', 'Bosques montanos sobre 1800 msnm'],
    },
  },
  'pristimantis penelopus': {
    scientificName: 'Pristimantis penelopus',
    author: 'Lynch, 1980',
    commonName: 'Pristimantis penelopus',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Craugastoridae',
    genus: 'Pristimantis',
    speciesEpithet: 'penelopus',
    iucn: 'LC',
    endemic: true,
    altitudeRange: { min: 1180, max: 1500 },
    habitat: 'Bosques montanos',
    activity: 'Nocturna',
    diet: 'Pequeños artrópodos',
    reproduction: 'Desarrollo directo',
    curiosity: 'Es endémica de la ladera oriental de la Cordillera Central en Colombia.',
    threats: ['Deforestación'],
    distribution: 'Antioquia, Tolima y Caldas, Colombia',
    whatIs: 'Pristimantis penelopus es una especie de anfibio anuro de la familia Craugastoridae. Esta especie es endémica de la ladera oriental de la Cordillera Central en Colombia. Habita en los departamentos de Antioquia, Tolima y Caldas entre 1 180 y 1 500 m de altitud.',
    synonyms: [],
    morphology: {
      dorsal: 'Coloración parda',
      ventral: 'Liso',
      size: 'Pequeño',
      diagnostics: ['Endémica de la Cordillera Central', 'Habita entre 1180 y 1500 m'],
    },
  },
  'dendropsophus bogerti': {
    scientificName: 'Dendropsophus bogerti',
    author: 'Cochran & Goin, 1961',
    commonName: 'Rana arborícola de Bogert',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Hylidae',
    genus: 'Dendropsophus',
    speciesEpithet: 'bogerti',
    iucn: 'LC',
    endemic: true,
    altitudeRange: { min: 0, max: 1000 },
    habitat: 'Montanos secos, marismas, estanques',
    activity: 'Nocturna',
    diet: 'Pequeños insectos',
    reproduction: 'Desove en cuerpos de agua lénticos',
    curiosity: 'Los machos emiten un canto nocturno característico para atraer a las hembras desde la vegetación.',
    threats: ['Destrucción de humedales'],
    distribution: 'Valles y tierras bajas de Colombia',
    whatIs: 'Dendropsophus bogerti es una especie de anfibios de la familia Hylidae. Es endémica de Colombia. Sus hábitats naturales incluyen montanos secos, marismas de agua dulce, corrientes intermitentes de agua, tierra arable, pastos, plantaciones, jardines rurales, áreas urbanas, zonas previamente boscosas ahora muy degradadas, estanques y tierras de irrigación.',
    synonyms: [],
    morphology: {
      dorsal: 'Verde o café claro',
      ventral: 'Vientre liso blanquecino',
      size: 'LHC: 2.0-3.0 cm',
      diagnostics: ['Dedos con discos adhesivos grandes', 'Ojos prominentes'],
    },
  },
  'dendropsophus microcephalus': {
    scientificName: 'Dendropsophus microcephalus',
    author: 'Cope, 1886',
    commonName: 'Ranita mísera',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Hylidae',
    genus: 'Dendropsophus',
    speciesEpithet: 'microcephalus',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 0, max: 1200 },
    habitat: 'Zonas abiertas inundables, vegetación baja',
    activity: 'Nocturna',
    diet: 'Pequeños insectos',
    reproduction: 'Desove en cuerpos de agua temporales',
    curiosity: 'Esta especie puede someterse a un cambio de color del día (tostado/amarillo con manchas oscuras) a la noche (amarillo claro).',
    threats: ['Contaminación de fuentes de agua'],
    distribution: 'Amplia desde México hasta el norte de Sudamérica',
    whatIs: 'La ranita mísera (Dendropsophus microcephalus) es una especie de anfibio de la familia Hylidae. La cabeza es plana y el hocico es redondeado y corto. Los ojos tienen pupilas elípticas dispuestas horizontalmente. Las fosas nasales están dirigidas lateralmente y el área entre las fosas nasales es algo cóncava. Esta especie puede someterse a un cambio de color. Durante la noche, el dorso es de color amarillo claro con varias marcas de color marrón o marrón claro. Durante el día, el dorso es de color tostado, amarillo o marrón claro con manchas más oscuras marrones o rojas.',
    synonyms: [],
    morphology: {
      dorsal: 'Cambio cromático (amarillo claro de noche, tostado de día)',
      ventral: 'Amarillo con muslos uniformemente amarillos',
      size: 'LHC: < 3 cm',
      diagnostics: ['Cabeza pequeña y plana', 'Muslos amarillos con línea marrón'],
    },
  },
  'hyloscirtus palmeri': {
    scientificName: 'Hyloscirtus palmeri',
    author: 'Boulenger, 1908',
    commonName: 'Rana torrente de Palmer',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Hylidae',
    genus: 'Hyloscirtus',
    speciesEpithet: 'palmeri',
    iucn: 'NT',
    endemic: false,
    altitudeRange: { min: 500, max: 2000 },
    habitat: 'Ríos, riachuelos y quebradas torrentosas',
    activity: 'Nocturna / Crepuscular',
    diet: 'Insectos asociados a cuerpos de agua',
    reproduction: 'Desove en riachuelos de corriente rápida',
    curiosity: 'Está estrictamente asociada a quebradas de corriente rápida y sirve como excelente bioindicadora de la calidad del agua.',
    threats: ['Destrucción de hábitat ribereño', 'Contaminación del agua'],
    distribution: 'Colombia, Costa Rica, Ecuador y Panamá',
    whatIs: 'La rana torrente de Palmer o rana arborícola de Palmer (Hyloscirtus palmeri) es una especie de anfibios de la familia Hylidae. Habita en Colombia, Costa Rica, Ecuador y Panamá. Sus hábitats naturales incluyen bosques tropicales o subtropicales secos y a baja altitud, montanos secos y ríos. Está amenazada por la destrucción de su hábitat natural.',
    synonyms: [],
    morphology: {
      dorsal: 'Dorso verde con reticulado oscuro',
      ventral: 'Vientre con tonos claros',
      size: 'LHC: 3.5-5.0 cm',
      diagnostics: ['Asociada a corrientes rápidas', 'Patrón de color verde reticulado'],
    },
  },
  'dendropsophus triangulum': {
    scientificName: 'Dendropsophus triangulum',
    author: '(Günther, 1869)',
    commonName: 'Ranita triángulo',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Hylidae',
    genus: 'Dendropsophus',
    speciesEpithet: 'triangulum',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 0, max: 1500 },
    habitat: 'Vegetación baja cerca de cuerpos de agua permanentes y temporales',
    activity: 'Nocturna',
    diet: 'Pequeños insectos y otros artrópodos',
    reproduction: 'Desove en charcas y cuerpos de agua de baja corriente',
    curiosity: 'Debe su nombre común al patrón triangular oscuro que suele marcarle el dorso, aunque varía bastante entre individuos.',
    threats: ['Pérdida de humedales', 'Contaminación de cuerpos de agua'],
    distribution: 'Cuenca amazónica y zonas bajas del norte de Sudamérica, incluida Colombia',
    whatIs: 'Dendropsophus triangulum es una rana pequeña de la familia Hylidae, de hábitos arborícolas y nocturnos. Se encuentra asociada a vegetación baja cerca de charcas y cuerpos de agua de poca corriente, donde los machos cantan para atraer parejas. Su coloración varía entre tonos amarillentos y pardos, con un patrón dorsal frecuentemente triangular que le da su nombre común.',
    synonyms: [],
    morphology: {
      dorsal: 'Fondo amarillento a pardo con patrón dorsal triangular variable',
      ventral: 'Vientre claro, granuloso',
      size: 'LHC: 2.0-2.8 cm',
      diagnostics: ['Patrón dorsal en forma de triángulo', 'Dedos con discos adhesivos pequeños'],
    },
  },
  'engystomops pustulosus': {
    scientificName: 'Engystomops pustulosus',
    author: '(Cope, 1864)',
    commonName: 'Rana túngara',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Leptodactylidae',
    genus: 'Engystomops',
    speciesEpithet: 'pustulosus',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 0, max: 1100 },
    habitat: 'Charcas temporales en zonas abiertas y bordes de bosque',
    activity: 'Nocturna',
    diet: 'Insectos pequeños',
    reproduction: 'Construye nidos de espuma flotante sobre el agua para proteger los huevos',
    curiosity: 'Su canto (un "quejido" seguido de "chasquidos") es uno de los mejor estudiados en biología de la comunicación animal: agregar chasquidos atrae más parejas, pero también más depredadores y parásitos.',
    threats: ['Pérdida de charcas temporales por urbanización'],
    distribution: 'Desde México hasta el norte de Suramérica, incluida la región Caribe y valles interandinos de Colombia',
    whatIs: 'La rana túngara (Engystomops pustulosus) es una especie pequeña y robusta de la familia Leptodactylidae, muy común en charcas temporales de zonas abiertas. Es célebre por su nido de espuma, que la hembra bate con las patas traseras mezclando aire, agua y proteínas para formar una masa flotante que protege los huevos y las larvas de depredadores y de la desecación.',
    synonyms: ['Physalaemus pustulosus'],
    morphology: {
      dorsal: 'Pardo grisáceo con pliegues y verrugas irregulares',
      ventral: 'Blanquecino',
      size: 'LHC: 2.5-3.5 cm',
      diagnostics: ['Piel dorsal muy verrugosa', 'Cuerpo robusto y hocico corto'],
    },
  },
  'rheobates palmatus': {
    scientificName: 'Rheobates palmatus',
    author: '(Werner, 1899)',
    commonName: 'Rana de torrente palmeada',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Aromobatidae',
    genus: 'Rheobates',
    speciesEpithet: 'palmatus',
    iucn: 'LC',
    endemic: true,
    altitudeRange: { min: 300, max: 2200 },
    habitat: 'Quebradas y riachuelos de montaña con corriente',
    activity: 'Diurna',
    diet: 'Pequeños artrópodos de la hojarasca y orillas de quebrada',
    reproduction: 'Desarrollo con estadio larvario en agua corriente; los renacuajos se adhieren a rocas',
    curiosity: 'A diferencia de muchas ranas nocturnas, es activa de día junto a quebradas, donde resulta relativamente fácil de observar sobre las rocas.',
    threats: ['Contaminación de quebradas', 'Deforestación de bosque ribereño'],
    distribution: 'Endémica de la cordillera de los Andes en Colombia',
    whatIs: 'Rheobates palmatus es una rana endémica de Colombia asociada a quebradas de montaña, donde se le encuentra activa durante el día sobre piedras cercanas a la corriente. Sus renacuajos tienen adaptaciones para fijarse a superficies rocosas en aguas de flujo rápido, una estrategia común entre las especies de "rana torrente" de los Andes.',
    synonyms: [],
    morphology: {
      dorsal: 'Pardo con manchas oscuras y una línea dorsolateral clara',
      ventral: 'Claro, a veces moteado',
      size: 'LHC: 2.5-3.5 cm',
      diagnostics: ['Dedos con membranas palmeadas parciales', 'Línea dorsolateral clara'],
    },
  },
  'scinax ruber': {
    scientificName: 'Scinax ruber',
    author: '(Laurenti, 1768)',
    commonName: 'Ranita de las cañadas',
    className: 'Amphibia',
    orderName: 'Anura',
    family: 'Hylidae',
    genus: 'Scinax',
    speciesEpithet: 'ruber',
    iucn: 'LC',
    endemic: false,
    altitudeRange: { min: 0, max: 1300 },
    habitat: 'Vegetación cerca de charcas, jardines y ambientes intervenidos',
    activity: 'Nocturna',
    diet: 'Insectos voladores y otros artrópodos pequeños',
    reproduction: 'Desove explosivo en charcas temporales tras las lluvias',
    curiosity: 'Es una de las especies de anfibios más tolerantes a la intervención humana, y suele encontrarse cerca de viviendas y en jardines urbanos.',
    threats: ['Ninguna amenaza significativa conocida — especie muy adaptable'],
    distribution: 'Ampliamente distribuida en Suramérica tropical, incluida buena parte de Colombia',
    whatIs: 'Scinax ruber es una rana arborícola pequeña y muy adaptable, capaz de vivir en ambientes alterados por el ser humano como jardines y zonas periurbanas, además de su hábitat natural de bosque. Se reproduce en charcas temporales, donde los machos forman coros ruidosos después de las lluvias.',
    synonyms: ['Hyla rubra'],
    morphology: {
      dorsal: 'Pardo a rojizo con manchas irregulares',
      ventral: 'Granuloso, blanquecino',
      size: 'LHC: 3.0-4.5 cm',
      diagnostics: ['Piel dorsal con textura ligeramente granular', 'Discos digitales bien desarrollados'],
    },
  },
};
